name: job_finder_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  flutter:
    sdk: flutter
  get: ^4.7.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_facebook_auth: ^7.1.0
  cloud_firestore: ^4.17.5
  file_picker: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^13.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/slideshow/
