// Autogenerated from Pigeon (v13.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "UserApi.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface PigeonUserDetails ()
+ (PigeonUserDetails *)fromList:(NSArray *)list;
+ (nullable PigeonUserDetails *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation PigeonUserDetails
+ (instancetype)makeWithName:(nullable NSString *)name
    email:(nullable NSString *)email {
  PigeonUserDetails* pigeonResult = [[PigeonUserDetails alloc] init];
  pigeonResult.name = name;
  pigeonResult.email = email;
  return pigeonResult;
}
+ (PigeonUserDetails *)fromList:(NSArray *)list {
  PigeonUserDetails *pigeonResult = [[PigeonUserDetails alloc] init];
  pigeonResult.name = GetNullableObjectAtIndex(list, 0);
  pigeonResult.email = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable PigeonUserDetails *)nullableFromList:(NSArray *)list {
  return (list) ? [PigeonUserDetails fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    self.name ?: [NSNull null],
    self.email ?: [NSNull null],
  ];
}
@end

@interface UserApiCodecReader : FlutterStandardReader
@end
@implementation UserApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [PigeonUserDetails fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface UserApiCodecWriter : FlutterStandardWriter
@end
@implementation UserApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[PigeonUserDetails class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface UserApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation UserApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[UserApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[UserApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *UserApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    UserApiCodecReaderWriter *readerWriter = [[UserApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void SetUpUserApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<UserApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.job_finder_app.UserApi.getUserDetails"
        binaryMessenger:binaryMessenger
        codec:UserApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getUserDetailsWithError:)], @"UserApi api (%@) doesn't respond to @selector(getUserDetailsWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSArray<PigeonUserDetails *> *output = [api getUserDetailsWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
