import 'package:flutter/material.dart';

final List<Map<String, dynamic>> jobJsonData = [
  {
    "id": "job-1111-0001",
    "company_id": "cmp-1111-aaaa-0001",
    "title": "Software Engineer",
    "name": "Facebook",
    "logo_url":
        "https://freebiehive.com/wp-content/uploads/2024/01/Facebook-Icon-PNG-758x473.jpg",
    "description": "We build Facebook products used by billions.",
    "responsibilities":
        "Full stack web/mobile application development. Implement UI using HTML/CSS/JS.",
    "requirements": "3+ years experience, JS, React, APIs",
    "bgColor": Colors.blue,
    "salary_min": 150000,
    "salary_max": 200000,
    "salary_text": "\$180,000/y",
    "currency": "USD",
    "salary_period": "year",
    "location_id": "loc-03",
    "location_name": "Phnom Penh, Cambodia",
    "job_type": "Full-Time",
    "office_type": "On-Site",
    "seniority": "Junior",
    "status": "Open",
    "posted_at": "2025-06-20T09:00:00Z",
    "updated_at": "2025-06-22T10:00:00Z",
    "featured": 1,
    "popularity_score": 35.5,
  },
  {
    "id": "job-1111-0002",
    "company_id": "cmp-1111-aaaa-0003",
    "title": "UX Intern",
    "name": "Spotify",
    "logo_url":
        "https://toppng.com/uploads/preview/spotify-logo-11609377845tapdd9ujdi.png",
    "description":
        "Design simple delightful product experiences for millions of listeners.",
    "responsibilities":
        "Work with senior designers, create wireframes and prototypes.",
    "requirements": "Portfolio, basic UX skills",
    "bgColor": Colors.green,
    "salary_min": 60000,
    "salary_max": 90000,
    "salary_text": "\$88,000/y",
    "currency": "USD",
    "salary_period": "year",
    "location_id": "loc-04",
    "location_name": "Meanchey, Phnom Penh",
    "job_type": "Full-Time",
    "office_type": "On-Site",
    "seniority": "Intern",
    "status": "Closed",
    "posted_at": "2025-05-10T09:00:00Z",
    "updated_at": "2025-05-30T12:00:00Z",
    "featured": 1,
    "popularity_score": 60.2,
  },
  {
    "id": "job-1111-0003",
    "company_id": "cmp-1111-aaaa-0004",
    "title": "Jr Executive",
    "name": "Google",
    "logo_url":
        "https://w7.pngwing.com/pngs/882/225/png-transparent-google-logo-google-logo-google-search-icon-google-text-logo-business-thumbnail.png",
    "description": "Operations and floor management at Burger King.",
    "responsibilities": "Customer service, inventory.",
    "requirements": "1+ year experience",
    "bgColor": Colors.blue,
    "salary_min": 90000,
    "salary_max": 98000,
    "salary_text": "\$96,000/y",
    "currency": "USD",
    "salary_period": "year",
    "location_id": "loc-04",
    "location_name": "Borey Sunway, Phnom Penh",
    "job_type": "Full-Time",
    "office_type": "On-Site",
    "seniority": "Junior",
    "status": "Open",
    "posted_at": "2025-04-15T08:00:00Z",
    "updated_at": "2025-04-16T08:00:00Z",
    "featured": 1,
    "popularity_score": 90.0,
  },
  {
    "id": "job-1111-0004",
    "company_id": "cmp-1111-aaaa-0005",
    "title": "Product Manager",
    "name": "Spotify",
    "logo_url":
        "https://toppng.com/uploads/preview/spotify-logo-11609377845tapdd9ujdi.png",
    "description": "Lead product roadmaps for audio devices.",
    "responsibilities": "Define roadmap, work with engineering and design.",
    "requirements": "2+ years PM experience",
    "bgColor": Colors.deepOrangeAccent,
    "salary_min": 80000,
    "salary_max": 90000,
    "salary_text": "\$84,000/y",
    "currency": "USD",
    "salary_period": "year",
    "location_id": "loc-09",
    "location_name": "Chba Ampov, Phnom Penh",
    "job_type": "Full-Time",
    "office_type": "On-Site",
    "seniority": "Mid",
    "status": "Open",
    "posted_at": "2025-03-20T08:00:00Z",
    "updated_at": "2025-04-01T09:00:00Z",
    "featured": 0,
    "popularity_score": 95.0,
  },
  {
    "id": "job-1111-0005",
    "company_id": "cmp-1111-aaaa-0006",
    "title": "UX Designer",
    "name": "Spotify",
    "logo_url":
        "https://toppng.com/uploads/preview/spotify-logo-11609377845tapdd9ujdi.png",
    "description":
        "Design platform interactions and visual design for creators.",
    "responsibilities": "Design systems, prototypes.",
    "requirements": "Portfolio required",
    "bgColor": Colors.green,
    "salary_min": 90000,
    "salary_max": 110000,
    "salary_text": "\$96,000/y",
    "currency": "USD",
    "salary_period": "year",
    "location_id": "loc-05",
    "location_name": "RTS Barbar TK, Phnom Penh",
    "job_type": "Full-Time",
    "office_type": "On-Site",
    "seniority": "Mid",
    "status": "Open",
    "posted_at": "2025-05-01T09:00:00Z",
    "updated_at": "2025-05-05T09:00:00Z",
    "featured": 0,
    "popularity_score": 70.1,
  },
  {
    "id": "job-1111-0006",
    "company_id": "cmp-1111-aaaa-0007",
    "title": "Full-Stack Developer",
    "name": "Facebook",
    "logo_url":
        "https://freebiehive.com/wp-content/uploads/2024/01/Facebook-Icon-PNG-758x473.jpg",
    "description": "Build internal tools and customer-facing web apps.",
    "responsibilities": "Backend and frontend development.",
    "requirements": "Node, React, SQL",
    "bgColor": Colors.deepOrangeAccent,
    "salary_min": 100000,
    "salary_max": 140000,
    "salary_text": "\$120,000/y",
    "currency": "USD",
    "salary_period": "year",
    "location_id": "loc-01",
    "location_name": "Camko, Phnom Penh",
    "job_type": "Full-Time",
    "office_type": "Remote",
    "seniority": "Senior",
    "status": "Open",
    "posted_at": "2025-07-01T09:00:00Z",
    "updated_at": "2025-07-05T09:00:00Z",
    "featured": 1,
    "popularity_score": 97.0,
  },
  {
    "id": "job-1111-0007",
    "company_id": "cmp-1111-aaaa-0008",
    "title": "Motion Designer",
    "name": "Dribbble",
    "logo_url":
        "https://images.vexels.com/media/users/3/137251/isolated/preview/4dd720f6ca6047fcf50bb14439e2f7af-dribbble-icon-logo.png?w=360",
    "description": "Create slick motion graphics for product launch videos.",
    "responsibilities": "Animate, prepare assets for marketing.",
    "requirements": "After Effects, portfolio",
    "bgColor": Colors.pink,
    "salary_min": 60000,
    "salary_max": 90000,
    "salary_text": "\$75,000/y",
    "currency": "USD",
    "salary_period": "year",
    "location_id": "loc-10",
    "location_name": "Phnom Penh, Cambodia",
    "job_type": "Part-Time",
    "office_type": "Remote",
    "seniority": "Mid",
    "status": "Open",
    "posted_at": "2025-06-15T09:00:00Z",
    "updated_at": "2025-06-20T09:00:00Z",
    "featured": 0,
    "popularity_score": 99.9,
  },
  {
    "id": "job-1111-0008",
    "company_id": "cmp-1111-aaaa-0009",
    "title": "Backend Developer",
    "name": "Facebook",
    "logo_url":
        "https://freebiehive.com/wp-content/uploads/2024/01/Facebook-Icon-PNG-758x473.jpg",
    "description": "Work on financial systems and integrations.",
    "responsibilities": "Design APIs, maintain services.",
    "requirements": "Go/Java, distributed systems",
    "bgColor": null,
    "salary_min": 130000,
    "salary_max": 160000,
    "salary_text": "\$145,000/y",
    "currency": "USD",
    "salary_period": "year",
    "location_id": "loc-06",
    "location_name": "Tuol Sangke, Phnom Penh",
    "job_type": "Full-Time",
    "office_type": "On-Site",
    "seniority": "Senior",
    "status": "Open",
    "posted_at": "2025-06-01T09:00:00Z",
    "updated_at": "2025-06-10T09:00:00Z",
    "featured": 0,
    "popularity_score": 65.4,
  },
  {
    "id": "job-1111-0009",
    "company_id": "cmp-1111-aaaa-0010",
    "title": "Product Designer",
    "name": "StartupX",
    "logo_url":
        "https://images-platform.99static.com/MIwBOyP3oRpZOfUQRBTCavMIfxc=/500x500/top/smart/99designs-contests-attachments/8/8747/attachment_8747702",
    "description": "End-to-end product design for mobile apps.",
    "responsibilities": "Research, design, test.",
    "requirements": "Strong portfolio, Figma",
    "bgColor": Colors.blue,
    "salary_min": 10000,
    "salary_max": 14000,
    "salary_text": "\$12,000/y",
    "currency": "USD",
    "salary_period": "year",
    "location_id": "loc-01",
    "location_name": "National Defense, Cambodia",
    "job_type": "Full-Time",
    "office_type": "On-Site",
    "seniority": "Junior",
    "status": "Open",
    "posted_at": "2025-02-25T09:00:00Z",
    "updated_at": "2025-03-01T09:00:00Z",
    "featured": 0,
    "popularity_score": 30.0,
  },
  {
    "id": "job-1111-0010",
    "company_id": "cmp-1111-aaaa-0002",
    "title": "Data Engineer",
    "name": "StartupX",
    "logo_url":
        "https://images-platform.99static.com/MIwBOyP3oRpZOfUQRBTCavMIfxc=/500x500/top/smart/99designs-contests-attachments/8/8747/attachment_8747702",
    "description":
        "- Build data pipelines at scale for search analytics.\n- Go/Java, distributed systems\n- Strong portfolio, Figma",
    "responsibilities": "ETL, data modeling, infra",
    "requirements": "Python, SQL, cloud",
    "bgColor": Colors.deepPurpleAccent,
    "salary_min": 125000,
    "salary_max": 170000,
    "salary_text": "\$150,000/y",
    "currency": "USD",
    "salary_period": "year",
    "location_id": "loc-02",
    "location_name": "National Defense, Cambodia",
    "job_type": "Full-Time",
    "office_type": "On-Site",
    "seniority": "Senior",
    "status": "Open",
    "posted_at": "2025-07-10T09:00:00Z",
    "updated_at": "2025-07-12T09:00:00Z",
    "featured": 1,
    "popularity_score": 99.2,
  },
];
