// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHOGC9vUH0lzAkgkq9EXdbCn3SL6oUi78',
    appId: '1:956661779958:web:55dc857373cca6bd030bd7',
    messagingSenderId: '956661779958',
    projectId: 'job-finder-app-b925d',
    authDomain: 'job-finder-app-b925d.firebaseapp.com',
    storageBucket: 'job-finder-app-b925d.firebasestorage.app',
    measurementId: 'G-CKJE8MDHG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv4GXgQnk7slEpzvrmWxMfzASiuTQ_mEE',
    appId: '1:956661779958:android:c55bce4f224595ec030bd7',
    messagingSenderId: '956661779958',
    projectId: 'job-finder-app-b925d',
    storageBucket: 'job-finder-app-b925d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcKOVD9SG7mGJNQN4bEu8fbxwRRbZXIGc',
    appId: '1:956661779958:ios:aeda9b34d0cc32bd030bd7',
    messagingSenderId: '956661779958',
    projectId: 'job-finder-app-b925d',
    storageBucket: 'job-finder-app-b925d.firebasestorage.app',
    iosBundleId: 'com.example.jobFinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcKOVD9SG7mGJNQN4bEu8fbxwRRbZXIGc',
    appId: '1:956661779958:ios:aeda9b34d0cc32bd030bd7',
    messagingSenderId: '956661779958',
    projectId: 'job-finder-app-b925d',
    storageBucket: 'job-finder-app-b925d.firebasestorage.app',
    iosBundleId: 'com.example.jobFinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHOGC9vUH0lzAkgkq9EXdbCn3SL6oUi78',
    appId: '1:956661779958:web:5d93efd6ff04c213030bd7',
    messagingSenderId: '956661779958',
    projectId: 'job-finder-app-b925d',
    authDomain: 'job-finder-app-b925d.firebaseapp.com',
    storageBucket: 'job-finder-app-b925d.firebasestorage.app',
    measurementId: 'G-H9G48ET0PZ',
  );

}